### ISSUE TITLE
FailedPreconditionError: Error while reading resource variable dense_1/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/kernel)

### ISSUE THREAD

**Issue by irdanish11** [irdanish11/Sentence-Prediction-using-LSTMs_aka-Language-Modeling#1]
[2020-03-11 03:44:10,845] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "plazapredict.py", line 34, in parameters
    return jsonify(predicted=sp.gen_sentence(num_sent=1,input_text=str(words)))
  File "/home/ec2-user/plazapredict/Contrib/Sentence_Prediction/sentence_prediction.py", line 196, in gen_sentence
    text,prob = main_itr(output_text, sent_prob)
  File "/home/ec2-user/plazapredict/Contrib/Sentence_Prediction/sentence_prediction.py", line 88, in main_itr
    tm_word, prob = gen_word(model, tokenizer, seq_len, output_text[count][0], num_gen_words=3)
  File "/home/ec2-user/plazapredict/Contrib/Sentence_Prediction/sentence_prediction.py", line 47, in gen_word
    ind, prob = get_prob(model,pad_encoded)
  File "/home/ec2-user/plazapredict/Contrib/Sentence_Prediction/sentence_prediction.py", line 22, in get_prob
    prob = model.predict_proba(pad_encoded,verbose=0)
  File "/usr/local/lib64/python3.7/site-packages/keras/engine/sequential.py", line 246, in predict_proba
    preds = self.predict(x, batch_size, verbose)
  File "/usr/local/lib64/python3.7/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/usr/local/lib64/python3.7/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in _call_
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in _call_
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/kernel)
         [[{{node dense_1/MatMul/ReadVariableOp}}]]
203.212.140.188 - - [11/Mar/2020 03:44:10] "GET /?words=door%20is%20broken HTTP/1.1" 500 -

**Comment by irdanish11** [comment]
I have resolved by creating a reference to the session that is used for loading the models and then to set it to be used by keras in each request. I.e. I have done the following:

```
from tensorflow.python.keras.backend import set_session
from tensorflow.python.keras.models import load_model

tf_config = some_custom_config
sess = tf.Session(config=tf_config)
graph = tf.get_default_graph()

# IMPORTANT: models have to be loaded AFTER SETTING THE SESSION for keras! 
# Otherwise, their weights will be unavailable in the threads after the session there has been set
set_session(sess)
model = load_model(...)
```

and then in each request (i.e. in each thread):

```
global sess
global graph
with graph.as_default():
    set_session(sess)
    model.predict(...)
```
